comments:
  active: false

complexity:
  active: false

potential-bugs:
  HasPlatformType:
    active: false
  UnsafeCallOnNullableType:
    active: false

exceptions:
  SwallowedException:
    active: false
  TooGenericExceptionCaught:
    active: false

formatting:
  NoWildcardImports:
    active: false

style:
  MandatoryBracesIfStatements:
    active: true
  MandatoryBracesLoops:
    active: true
  WildcardImport:
    active: false
  UseOrEmpty:
    active: false
  UnnecessaryAbstractClass:
    active: false
  FunctionOnlyReturningConstant:
    active: false
  SerialVersionUIDInSerializableClass:
    active: false
  ForbiddenComment:
    active: false
  UnusedParameter:
    active: false
  UnusedPrivateMember:
    active: false
  UnusedPrivateProperty:
    active: false
  ThrowsCount:
    active: false

naming:
  NoNameShadowing:
    active: false
  PackageNaming:
    active: false
